### ISSUE TITLE
Unnecessary if statement and go out range

### ISSUE THREAD

**Issue by JamesBOT212** [lamik/DS18B20_STM32_HAL#1]
https://github.com/lamik/DS18B20_STM32_HAL/blob/a97b5031395949e5c7c4847c2add845cdcf34fe3/Src/ds18b20.c#L288

I observed that you don't need to check DS family, because you do it inside DS18B20_SetResolution function. If I am correct, it means that in this if statement you are trying to check only one DS for "i" out of range.

**Comment by lamik** [comment]
Yes, you are right. This check is unnecessary. And the iterator s wrong as well. I have fixed that. Sorry for late response :)
